// GET_ALARM_BY_ID
export const GET_ALARM_BY_ID = "GET_ALARM_BY_ID"
export const GET_ALARM_BY_ID_SUCCESS = "GET_ALARM_BY_ID_SUCCESS"
export const GET_ALARM_BY_ID_FAIL = "GET_ALARM_BY_ID_FAIL"

// DELETE_ALARM
export const DELETE_ALARM = "DELETE_ALARM"
export const DELETE_ALARM_SUCCESS = "DELETE_ALARM_SUCCESS"
export const DELETE_ALARM_FAIL = "DELETE_ALARM_FAIL"

// GET_ALARM_TYPES
export const GET_ALARM_TYPES = "GET_ALARM_TYPES"
export const GET_ALARM_TYPES_SUCCESS = "GET_ALARM_TYPES_SUCCESS"
export const GET_ALARM_TYPES_FAIL = "GET_ALARM_TYPES_FAIL"

// ADD_ALARM
export const ADD_ALARM = "ADD_ALARM"
export const ADD_ALARM_SUCCESS = "ADD_ALARM_SUCCESS"
export const ADD_ALARM_FAIL = "ADD_ALARM_FAIL"

// UPDATE_ALARM
export const UPDATE_ALARM = "UPDATE_ALARM"
export const UPDATE_ALARM_SUCCESS = "UPDATE_ALARM_SUCCESS"
export const UPDATE_ALARM_FAIL = "UPDATE_ALARM_FAIL"

// GET_ACTIVE_ALARMS
export const GET_ACTIVE_ALARMS = "GET_ACTIVE_ALARMS"
export const GET_ACTIVE_ALARMS_SUCCESS = "GET_ACTIVE_ALARMS_SUCCESS"
export const GET_ACTIVE_ALARMS_FAIL = "GET_ACTIVE_ALARMS_FAIL"

// GET_ALARM_HISTORY
export const GET_ALARM_HISTORY = "GET_ALARM_HISTORY"
export const GET_ALARM_HISTORY_SUCCESS = "GET_ALARM_HISTORY_SUCCESS"
export const GET_ALARM_HISTORY_FAIL = "GET_ALARM_HISTORY_FAIL"

// GET_ALARM_COUNTS
export const GET_ALARM_COUNTS = "GET_ALARM_COUNTS"
export const GET_ALARM_COUNTS_SUCCESS = "GET_ALARM_COUNTS_SUCCESS"
export const GET_ALARM_COUNTS_FAIL = "GET_ALARM_COUNTS_FAIL"

// GET_TOTAL_ALARM_TYPES_BY_ID
export const GET_TOTAL_ALARM_TYPES_BY_ID = "GET_TOTAL_ALARM_TYPES_BY_ID"
export const GET_TOTAL_ALARM_TYPES_BY_ID_SUCCESS = "GET_TOTAL_ALARM_TYPES_BY_ID_SUCCESS"
export const GET_TOTAL_ALARM_TYPES_BY_ID_FAIL = "GET_TOTAL_ALARM_TYPES_BY_ID_FAIL"

// GET_ALARM_LOG_HISTORY
export const GET_ALARM_LOG_HISTORY = "GET_ALARM_LOG_HISTORY"
export const GET_ALARM_LOG_HISTORY_SUCCESS = "GET_ALARM_LOG_HISTORY_SUCCESS"
export const GET_ALARM_LOG_HISTORY_FAIL = "GET_ALARM_LOG_HISTORY_FAIL"
